-- Uganda EMHSLU 2023 additional medications
INSERT INTO medications (name, is_active) VALUES
  -- Malaria
  ('Artemether/Lumefantrine 20/120mg', TRUE),
  ('Artemether/Lumefantrine 80/480mg', TRUE),
  ('Coartem 20/120mg', TRUE),
  ('Coartem 80/480mg', TRUE),
  ('Artesunate 50mg', TRUE),
  ('Artesunate 100mg', TRUE),
  ('Artesunate 200mg', TRUE),
  ('Artesunate Injection 60mg', TRUE),
  ('Artemether Injection 80mg', TRUE),
  ('Quinine 300mg', TRUE),
  ('Quinine Sulphate 300mg', TRUE),
  ('Quinine Injection 600mg/2ml', TRUE),
  ('Dihydroartemisinin/Piperaquine 40/320mg', TRUE),
  ('Amodiaquine 200mg', TRUE),
  ('Sulfadoxine/Pyrimethamine 500/25mg', TRUE),
  ('Fansidar 500/25mg', TRUE),
  -- Epilepsy
  ('Phenobarbital 30mg', TRUE),
  ('Phenobarbital 60mg', TRUE),
  ('Phenobarbital 100mg', TRUE),
  ('Phenytoin 50mg', TRUE),
  ('Phenytoin 100mg', TRUE),
  ('Levetiracetam 250mg', TRUE),
  ('Levetiracetam 500mg', TRUE),
  ('Levetiracetam 1000mg', TRUE),
  ('Keppra 500mg', TRUE),
  ('Ethosuximide 250mg', TRUE),
  ('Gabapentin 100mg', TRUE),
  ('Gabapentin 300mg', TRUE),
  ('Gabapentin 400mg', TRUE),
  -- Hypertension/Obstetric
  ('Captopril 12.5mg', TRUE),
  ('Captopril 25mg', TRUE),
  ('Captopril 50mg', TRUE),
  ('Methyldopa 250mg', TRUE),
  ('Methyldopa 500mg', TRUE),
  ('Hydralazine 25mg', TRUE),
  ('Hydralazine 50mg', TRUE),
  ('Hydralazine Injection 20mg', TRUE),
  ('Labetalol 100mg', TRUE),
  ('Labetalol 200mg', TRUE),
  ('Magnesium Sulphate 50% Injection', TRUE),
  -- Asthma
  ('Aminophylline 100mg', TRUE),
  ('Aminophylline 200mg', TRUE),
  ('Aminophylline Injection 250mg/10ml', TRUE),
  ('Salbutamol Syrup 2mg/5ml', TRUE),
  ('Salbutamol Tablets 2mg', TRUE),
  ('Salbutamol Tablets 4mg', TRUE),
  -- Mental Health
  ('Chlorpromazine 25mg', TRUE),
  ('Chlorpromazine 50mg', TRUE),
  ('Chlorpromazine 100mg', TRUE),
  ('Fluphenazine Decanoate 25mg/ml', TRUE),
  ('Trifluoperazine 5mg', TRUE),
  ('Thioridazine 25mg', TRUE),
  ('Thioridazine 100mg', TRUE),
  ('Trihexyphenidyl 2mg', TRUE),
  ('Trihexyphenidyl 5mg', TRUE),
  ('Procyclidine 5mg', TRUE),
  ('Biperiden 2mg', TRUE),
  -- HIV ARVs Uganda
  ('Dolutegravir/Lamivudine 50/300mg', TRUE),
  ('Abacavir/Lamivudine 600/300mg', TRUE),
  ('Abacavir/Lamivudine/Dolutegravir', TRUE),
  ('Efavirenz/Lamivudine/Tenofovir 600/300/300mg', TRUE),
  ('TLE (Tenofovir/Lamivudine/Efavirenz)', TRUE),
  ('Zidovudine/Lamivudine 300/150mg', TRUE),
  ('Zidovudine/Lamivudine/Nevirapine', TRUE),
  ('Rilpivirine 25mg', TRUE),
  ('Raltegravir 400mg', TRUE),
  ('Cabotegravir 30mg', TRUE),
  -- TB
  ('Rifabutin 150mg', TRUE),
  ('Bedaquiline 100mg', TRUE),
  ('Delamanid 50mg', TRUE),
  ('Linezolid 300mg', TRUE),
  ('Linezolid 600mg', TRUE),
  ('Clofazimine 50mg', TRUE),
  ('Clofazimine 100mg', TRUE),
  ('Cycloserine 250mg', TRUE),
  ('Moxifloxacin 400mg', TRUE),
  ('Levofloxacin 250mg', TRUE),
  ('Levofloxacin 500mg', TRUE),
  ('Levofloxacin 750mg', TRUE),
  ('Pyridoxine 25mg', TRUE),
  ('Pyridoxine 50mg', TRUE),
  ('Pyridoxine 100mg', TRUE),
  -- Antiparasitics
  ('Albendazole 200mg', TRUE),
  ('Albendazole 400mg', TRUE),
  ('Mebendazole 100mg', TRUE),
  ('Mebendazole 500mg', TRUE),
  ('Ivermectin 3mg', TRUE),
  ('Ivermectin 6mg', TRUE),
  ('Praziquantel 150mg', TRUE),
  ('Praziquantel 600mg', TRUE),
  ('Diethylcarbamazine 50mg', TRUE),
  ('Diethylcarbamazine 100mg', TRUE),
  ('Niclosamide 500mg', TRUE),
  ('Pentamidine 200mg Injection', TRUE),
  ('Nifurtimox 120mg', TRUE),
  -- Antibiotics
  ('Ampicillin 250mg', TRUE),
  ('Ampicillin 500mg', TRUE),
  ('Ampicillin Injection 1g', TRUE),
  ('Benzylpenicillin 1MU Injection', TRUE),
  ('Benzathine Penicillin 1.2MU Injection', TRUE),
  ('Benzathine Penicillin 2.4MU Injection', TRUE),
  ('Gentamicin 80mg Injection', TRUE),
  ('Gentamicin 160mg Injection', TRUE),
  ('Trimethoprim 200mg', TRUE),
  ('Chloramphenicol 250mg', TRUE),
  ('Ceftriaxone 1g Injection', TRUE),
  ('Cefotaxime 1g Injection', TRUE),
  ('Moxifloxacin 400mg', TRUE),
  ('Tetracycline 250mg', TRUE),
  ('Tetracycline 500mg', TRUE),
  -- Sickle Cell
  ('Hydroxyurea 500mg', TRUE),
  ('Hydroxycarbamide 500mg', TRUE),
  ('Deferasirox 250mg', TRUE),
  ('Deferasirox 500mg', TRUE),
  -- Antifungals
  ('Nystatin Suspension 100,000IU/ml', TRUE),
  ('Griseofulvin 125mg', TRUE),
  ('Griseofulvin 500mg', TRUE),
  ('Amphotericin B Injection', TRUE),
  ('Voriconazole 200mg', TRUE),
  ('Fluconazole 50mg', TRUE),
  -- Rheumatology
  ('Leflunomide 10mg', TRUE),
  ('Leflunomide 20mg', TRUE),
  ('Azathioprine 50mg', TRUE),
  ('Chloroquine Phosphate 250mg', TRUE),
  ('Indomethacin 25mg', TRUE),
  ('Indomethacin 50mg', TRUE),
  ('Celecoxib 100mg', TRUE),
  ('Celecoxib 200mg', TRUE),
  -- Thyroid
  ('Propylthiouracil 50mg', TRUE),
  ('Propylthiouracil 100mg', TRUE),
  -- Reproductive
  ('Oxytocin 10IU Injection', TRUE),
  ('Misoprostol 200mcg', TRUE),
  ('Misoprostol 25mcg', TRUE),
  ('Medroxyprogesterone 150mg Injection', TRUE),
  -- Chronic Kidney
  ('Erythropoietin 2000IU Injection', TRUE),
  ('Erythropoietin 4000IU Injection', TRUE),
  ('Calcium Acetate 667mg', TRUE),
  ('Sevelamer 800mg', TRUE),
  ('Sodium Bicarbonate 500mg', TRUE),
  -- Vitamins
  ('Ferrous Sulphate Syrup 25mg/ml', TRUE),
  ('Iron/Folic Acid 200mg/0.4mg', TRUE),
  ('Vitamin A 200,000IU Capsule', TRUE),
  ('Vitamin C 500mg', TRUE),
  ('Thiamine 100mg', TRUE),
  ('Zinc Sulphate 20mg', TRUE),
  ('Oral Rehydration Salts', TRUE),
  -- Cardiovascular
  ('Amiodarone 100mg', TRUE),
  ('Amiodarone 200mg', TRUE),
  ('Verapamil 40mg', TRUE),
  ('Verapamil 80mg', TRUE),
  ('Diltiazem 60mg', TRUE),
  ('Diltiazem 90mg', TRUE),
  ('Adrenaline 1mg/ml Injection', TRUE),
  ('Glyceryl Trinitrate Spray', TRUE),
  ('Glyceryl Trinitrate Tablets 0.5mg', TRUE),
  ('Eplerenone 25mg', TRUE),
  ('Eplerenone 50mg', TRUE),
  ('Ivabradine 5mg', TRUE),
  -- GI
  ('Sucralfate 1g', TRUE),
  ('Mesalazine 400mg', TRUE),
  ('Hyoscine Butylbromide 10mg', TRUE),
  ('Buscopan 10mg', TRUE),
  ('Activated Charcoal', TRUE)
ON CONFLICT DO NOTHING;
