import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import 'package:flutter/services.dart' show rootBundle;
import '../models/member.dart';
import '../models/vital.dart';
import '../models/medication.dart';
import '../models/lab_test.dart';

class PdfService {
  static Future<void> exportHealthReport({
    required Member member,
    required List<Vital> vitals,
    required List<Medication> medications,
    required List<LabTest> labTests,
  }) async {
    final doc = pw.Document();
    final generatedDate = DateFormat('d MMMM yyyy, HH:mm').format(DateTime.now());
    final last5Vitals = vitals.take(5).toList();
    final activeMeds = medications.where((m) => !m.isCompleted).toList();
    final last3Labs = labTests.take(3).toList();

    // Load the app logo for the PDF header
    pw.ImageProvider? logoImage;
    try {
      final logoData = await rootBundle.load('assets/images/app_icon.jpg');
      logoImage = pw.MemoryImage(logoData.buffer.asUint8List());
    } catch (_) {
      // Fall back to text placeholder if logo can't be loaded
    }

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        header: (ctx) => _buildHeader(member, generatedDate, logoImage),
        footer: (_) => _buildFooter(),
        build: (ctx) => [
          pw.SizedBox(height: 16),
          _memberInfoSection(member),
          pw.SizedBox(height: 20),
          _vitalsSection(last5Vitals),
          pw.SizedBox(height: 20),
          _medicationsSection(activeMeds),
          pw.SizedBox(height: 20),
          _labResultsSection(last3Labs),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async => doc.save(),
      name: 'health_report_${member.memberNumber}.pdf',
    );
  }

  static pw.Widget _buildHeader(Member member, String date, pw.ImageProvider? logoImage) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 12),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: PdfColors.blue900, width: 2),
        ),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          // Logo
          logoImage != null
              ? pw.ClipRRect(
                  horizontalRadius: 8,
                  verticalRadius: 8,
                  child: pw.Image(logoImage, width: 48, height: 48),
                )
              : pw.Container(
                  width: 48,
                  height: 48,
                  decoration: pw.BoxDecoration(
                    color: PdfColors.blue900,
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
                  ),
                  child: pw.Center(
                    child: pw.Text(
                      'S',
                      style: pw.TextStyle(
                        color: PdfColors.white,
                        fontSize: 28,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                ),
          pw.SizedBox(width: 14),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'SanCare+',
                  style: pw.TextStyle(
                    color: PdfColors.blue900,
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.Text(
                  'Health Report',
                  style: const pw.TextStyle(
                    color: PdfColors.grey700,
                    fontSize: 11,
                  ),
                ),
              ],
            ),
          ),
          pw.Text(
            'Generated: $date',
            style: const pw.TextStyle(
              color: PdfColors.grey600,
              fontSize: 9,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildFooter() {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          top: pw.BorderSide(color: PdfColors.grey300),
        ),
      ),
      child: pw.Center(
        child: pw.Text(
          'Generated by SanCare+ App  •  Confidential',
          style: const pw.TextStyle(color: PdfColors.grey500, fontSize: 8),
        ),
      ),
    );
  }

  static pw.Widget _memberInfoSection(Member member) {
    return _section(
      title: 'Member Information',
      child: pw.Table(
        columnWidths: const {
          0: pw.FlexColumnWidth(1.2),
          1: pw.FlexColumnWidth(2),
          2: pw.FlexColumnWidth(1.2),
          3: pw.FlexColumnWidth(2),
        },
        children: [
          _tableRow('Full Name', member.fullName, 'Member Number', member.memberNumber),
          _tableRow('Scheme', member.planType, 'Date of Birth', member.dateOfBirth ?? '—'),
          _tableRow('Email', member.email ?? '—', 'Phone', member.phone ?? '—'),
          pw.TableRow(
            children: [
              _labelCell('Conditions'),
              pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 4, horizontal: 6),
                child: pw.Text(
                  member.conditions.isEmpty ? 'None recorded' : member.conditions.join(', '),
                  style: const pw.TextStyle(fontSize: 10),
                ),
              ),
              _labelCell(''),
              _valueCell(''),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _vitalsSection(List<Vital> vitals) {
    if (vitals.isEmpty) {
      return _section(
        title: 'Recent Vitals',
        child: pw.Text('No vitals recorded.', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
      );
    }

    return _section(
      title: 'Recent Vitals (Last ${vitals.length} Readings)',
      child: pw.Table(
        border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
        columnWidths: const {
          0: pw.FlexColumnWidth(1.5),
          1: pw.FlexColumnWidth(1.2),
          2: pw.FlexColumnWidth(1),
          3: pw.FlexColumnWidth(1),
          4: pw.FlexColumnWidth(1),
          5: pw.FlexColumnWidth(1),
        },
        children: [
          pw.TableRow(
            decoration: const pw.BoxDecoration(color: PdfColors.blue900),
            children: [
              _headerCell('Date'),
              _headerCell('Blood Pressure'),
              _headerCell('Heart Rate'),
              _headerCell('Glucose'),
              _headerCell('Weight'),
              _headerCell('O₂ Sat'),
            ],
          ),
          ...vitals.map((v) => pw.TableRow(
            children: [
              _dataCell(DateFormat('dd/MM/yy').format(v.loggedAt)),
              _dataCell(v.bpString != '--' ? v.bpString : '—'),
              _dataCell(v.heartRate != null ? '${v.heartRate} bpm' : '—'),
              _dataCell(v.bloodSugar != null ? '${v.bloodSugar!.toStringAsFixed(1)} mmol' : '—'),
              _dataCell(v.weight != null ? '${v.weight!.toStringAsFixed(1)} kg' : '—'),
              _dataCell(v.oxygenSaturation != null ? '${v.oxygenSaturation!.toStringAsFixed(0)}%' : '—'),
            ],
          )),
        ],
      ),
    );
  }

  static pw.Widget _medicationsSection(List<Medication> meds) {
    if (meds.isEmpty) {
      return _section(
        title: 'Active Medications',
        child: pw.Text('No active medications.', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
      );
    }

    return _section(
      title: 'Active Medications',
      child: pw.Table(
        border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
        columnWidths: const {
          0: pw.FlexColumnWidth(2),
          1: pw.FlexColumnWidth(1),
          2: pw.FlexColumnWidth(1.5),
        },
        children: [
          pw.TableRow(
            decoration: const pw.BoxDecoration(color: PdfColors.blue900),
            children: [
              _headerCell('Medication'),
              _headerCell('Dosage'),
              _headerCell('Frequency'),
            ],
          ),
          ...meds.map((m) => pw.TableRow(
            children: [
              _dataCell(m.name),
              _dataCell(m.dosage),
              _dataCell(m.frequency),
            ],
          )),
        ],
      ),
    );
  }

  static pw.Widget _labResultsSection(List<LabTest> labs) {
    if (labs.isEmpty) {
      return _section(
        title: 'Lab Results',
        child: pw.Text('No lab results recorded.', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
      );
    }

    return _section(
      title: 'Recent Lab Results',
      child: pw.Table(
        border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
        columnWidths: const {
          0: pw.FlexColumnWidth(2.5),
          1: pw.FlexColumnWidth(1),
          2: pw.FlexColumnWidth(1.5),
          3: pw.FlexColumnWidth(1.5),
        },
        children: [
          pw.TableRow(
            decoration: const pw.BoxDecoration(color: PdfColors.blue900),
            children: [
              _headerCell('Test'),
              _headerCell('Status'),
              _headerCell('Due Date'),
              _headerCell('Completed'),
            ],
          ),
          ...labs.map((l) => pw.TableRow(
            children: [
              _dataCell(l.testTypeLabel),
              _dataCell(l.status.toUpperCase()),
              _dataCell(l.formattedDueDate),
              _dataCell(l.completedAt != null
                  ? DateFormat('dd/MM/yy').format(l.completedAt!)
                  : '—'),
            ],
          )),
        ],
      ),
    );
  }

  // ── Helpers ──────────────────────────────────────────────────────────────

  static pw.Widget _section({required String title, required pw.Widget child}) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Container(
          width: double.infinity,
          padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
          decoration: pw.BoxDecoration(
            color: PdfColors.blue50,
            border: const pw.Border(
              left: pw.BorderSide(color: PdfColors.blue900, width: 3),
            ),
          ),
          child: pw.Text(
            title,
            style: pw.TextStyle(
              color: PdfColors.blue900,
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ),
        pw.SizedBox(height: 8),
        child,
      ],
    );
  }

  static pw.TableRow _tableRow(String l1, String v1, String l2, String v2) {
    return pw.TableRow(children: [
      _labelCell(l1),
      _valueCell(v1),
      _labelCell(l2),
      _valueCell(v2),
    ]);
  }

  static pw.Widget _labelCell(String text) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 4, horizontal: 6),
        child: pw.Text(
          text,
          style: pw.TextStyle(
            fontSize: 9,
            color: PdfColors.grey700,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
      );

  static pw.Widget _valueCell(String text) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 4, horizontal: 6),
        child: pw.Text(text, style: const pw.TextStyle(fontSize: 10)),
      );

  static pw.Widget _headerCell(String text) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 5, horizontal: 6),
        child: pw.Text(
          text,
          style: pw.TextStyle(
            fontSize: 9,
            color: PdfColors.white,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
      );

  static pw.Widget _dataCell(String text) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 4, horizontal: 6),
        child: pw.Text(text, style: const pw.TextStyle(fontSize: 9)),
      );
}
