/// Common medications used in Uganda and Sub-Saharan Africa (EMHSLU 2023).
/// Includes INN generic names, local brand names, and common strengths.
const List<String> kCommonMedications = [
  // ── Analgesics / Antipyretics ─────────────────────────────────────────────
  'Paracetamol',
  'Paracetamol 500mg',
  'Paracetamol 1000mg',
  'Paracetamol 120mg/5ml Syrup',
  'Panado 500mg',
  'Panado Syrup',
  'Adco-Paracetamol 500mg',
  'Grandpa Headache Powder',
  'Ibuprofen',
  'Ibuprofen 200mg',
  'Ibuprofen 400mg',
  'Ibuprofen 600mg',
  'Brufen 400mg',
  'Nurofen 200mg',
  'Diclofenac',
  'Diclofenac 50mg',
  'Diclofenac 75mg',
  'Voltaren 50mg',
  'Naproxen 250mg',
  'Naproxen 500mg',
  'Aspirin 75mg',
  'Aspirin 100mg',
  'Aspirin 300mg',
  'Tramadol 50mg',
  'Tramadol 100mg',
  'Codeine 30mg',
  'Morphine 10mg',

  // ── Diabetes ──────────────────────────────────────────────────────────────
  'Metformin',
  'Metformin 500mg',
  'Metformin 850mg',
  'Metformin 1000mg',
  'Glucophage 500mg',
  'Glucophage 850mg',
  'Glucophage XR 1000mg',
  'Glibenclamide 2.5mg',
  'Glibenclamide 5mg',
  'Gliclazide 30mg',
  'Gliclazide 60mg',
  'Gliclazide 80mg',
  'Diamicron MR 30mg',
  'Glimepiride 1mg',
  'Glimepiride 2mg',
  'Glimepiride 4mg',
  'Sitagliptin 100mg',
  'Januvia 100mg',
  'Empagliflozin 10mg',
  'Empagliflozin 25mg',
  'Jardiance 10mg',
  'Dapagliflozin 10mg',
  'Forxiga 10mg',
  'Pioglitazone 15mg',
  'Pioglitazone 30mg',
  'Acarbose 50mg',
  'Acarbose 100mg',
  'Insulin Glargine',
  'Insulin Aspart',
  'Insulin Lispro',
  'Insulin NPH',
  'Insulin Regular',
  'Mixtard 30/70',
  'NovoMix 30',
  'Lantus SoloStar',
  'Ozempic 0.5mg',
  'Ozempic 1mg',
  'Victoza 1.2mg',
  'Victoza 1.8mg',

  // ── Hypertension / Cardiovascular ─────────────────────────────────────────
  'Amlodipine',
  'Amlodipine 5mg',
  'Amlodipine 10mg',
  'Lisinopril',
  'Lisinopril 5mg',
  'Lisinopril 10mg',
  'Lisinopril 20mg',
  'Enalapril',
  'Enalapril 5mg',
  'Enalapril 10mg',
  'Enalapril 20mg',
  'Perindopril 5mg',
  'Perindopril 10mg',
  'Coversyl 5mg',
  'Ramipril 5mg',
  'Ramipril 10mg',
  'Losartan',
  'Losartan 50mg',
  'Losartan 100mg',
  'Cozaar 50mg',
  'Valsartan 80mg',
  'Valsartan 160mg',
  'Telmisartan 40mg',
  'Telmisartan 80mg',
  'Irbesartan 150mg',
  'Irbesartan 300mg',
  'Hydrochlorothiazide 12.5mg',
  'Hydrochlorothiazide 25mg',
  'Chlorthalidone 25mg',
  'Indapamide 1.5mg',
  'Indapamide 2.5mg',
  'Metoprolol 25mg',
  'Metoprolol 50mg',
  'Metoprolol 100mg',
  'Bisoprolol 2.5mg',
  'Bisoprolol 5mg',
  'Bisoprolol 10mg',
  'Carvedilol 6.25mg',
  'Carvedilol 12.5mg',
  'Carvedilol 25mg',
  'Atenolol 50mg',
  'Atenolol 100mg',
  'Furosemide',
  'Furosemide 20mg',
  'Furosemide 40mg',
  'Furosemide 80mg',
  'Lasix 40mg',
  'Spironolactone 25mg',
  'Spironolactone 50mg',
  'Aldactone 25mg',
  'Nifedipine 10mg',
  'Nifedipine 20mg',
  'Nifedipine XL 30mg',
  'Felodipine 5mg',
  'Felodipine 10mg',
  'Isosorbide Mononitrate 20mg',
  'Isosorbide Mononitrate 40mg',
  'Isosorbide Dinitrate 5mg',
  'Digoxin 0.125mg',
  'Digoxin 0.25mg',
  'Warfarin 1mg',
  'Warfarin 2mg',
  'Warfarin 5mg',
  'Apixaban 2.5mg',
  'Apixaban 5mg',
  'Eliquis 5mg',
  'Rivaroxaban 10mg',
  'Rivaroxaban 15mg',
  'Rivaroxaban 20mg',
  'Xarelto 20mg',
  'Dabigatran 110mg',
  'Dabigatran 150mg',
  'Heparin 5000IU',
  'Clopidogrel 75mg',
  'Plavix 75mg',
  'Ticagrelor 90mg',

  // ── Cholesterol / Lipids ──────────────────────────────────────────────────
  'Atorvastatin',
  'Atorvastatin 10mg',
  'Atorvastatin 20mg',
  'Atorvastatin 40mg',
  'Atorvastatin 80mg',
  'Lipitor 20mg',
  'Simvastatin 10mg',
  'Simvastatin 20mg',
  'Simvastatin 40mg',
  'Rosuvastatin 10mg',
  'Rosuvastatin 20mg',
  'Rosuvastatin 40mg',
  'Crestor 10mg',
  'Pravastatin 20mg',
  'Pravastatin 40mg',
  'Fenofibrate 145mg',
  'Fenofibrate 200mg',
  'Ezetimibe 10mg',

  // ── Asthma / COPD / Respiratory ───────────────────────────────────────────
  'Salbutamol Inhaler',
  'Salbutamol 100mcg Inhaler',
  'Ventolin Inhaler',
  'Ventolin Nebule 2.5mg',
  'Budesonide Inhaler',
  'Budesonide 200mcg Inhaler',
  'Pulmicort 200mcg',
  'Fluticasone Inhaler',
  'Fluticasone 125mcg Inhaler',
  'Flixotide 125mcg',
  'Beclomethasone 100mcg Inhaler',
  'Salmeterol/Fluticasone Inhaler',
  'Seretide 125mcg',
  'Seretide 250mcg',
  'Formoterol/Budesonide Inhaler',
  'Symbicort 160/4.5mcg',
  'Tiotropium 18mcg',
  'Spiriva 18mcg',
  'Montelukast 5mg',
  'Montelukast 10mg',
  'Singulair 10mg',
  'Ipratropium Inhaler',
  'Atrovent Inhaler',
  'Theophylline 200mg',
  'Theophylline 300mg',
  'Prednisolone 5mg',
  'Prednisolone 10mg',
  'Prednisolone 20mg',
  'Prednisolone 25mg Syrup',
  'Prednisone 5mg',
  'Prednisone 10mg',
  'Prednisone 20mg',
  'Prednisone 50mg',

  // ── Antibiotics ───────────────────────────────────────────────────────────
  'Amoxicillin 250mg',
  'Amoxicillin 500mg',
  'Amoxicillin 125mg/5ml Syrup',
  'Augmentin 375mg',
  'Augmentin 625mg',
  'Amoxicillin/Clavulanate 625mg',
  'Azithromycin 250mg',
  'Azithromycin 500mg',
  'Zithromax 500mg',
  'Clarithromycin 250mg',
  'Clarithromycin 500mg',
  'Erythromycin 250mg',
  'Erythromycin 500mg',
  'Doxycycline 100mg',
  'Ciprofloxacin 250mg',
  'Ciprofloxacin 500mg',
  'Ciprobay 500mg',
  'Metronidazole 200mg',
  'Metronidazole 400mg',
  'Flagyl 400mg',
  'Cotrimoxazole 480mg',
  'Cotrimoxazole 960mg',
  'Bactrim 960mg',
  'Flucloxacillin 250mg',
  'Flucloxacillin 500mg',
  'Clindamycin 150mg',
  'Clindamycin 300mg',
  'Nitrofurantoin 50mg',
  'Nitrofurantoin 100mg',
  'Cephalexin 250mg',
  'Cephalexin 500mg',
  'Cefuroxime 250mg',
  'Cefuroxime 500mg',
  'Penicillin VK 250mg',
  'Penicillin VK 500mg',

  // ── HIV / ARVs ────────────────────────────────────────────────────────────
  'Tenofovir/Lamivudine/Dolutegravir',
  'TLD (Tenofovir/Lamivudine/Dolutegravir)',
  'Tenofovir 300mg',
  'Lamivudine 150mg',
  'Lamivudine 300mg',
  'Dolutegravir 50mg',
  'Efavirenz 600mg',
  'Nevirapine 200mg',
  'Lopinavir/Ritonavir 200/50mg',
  'Kaletra 200/50mg',
  'Atazanavir 300mg',
  'Darunavir 600mg',
  'Abacavir 300mg',
  'Zidovudine 300mg',
  'Emtricitabine/Tenofovir',
  'Truvada',
  'Biktarvy',

  // ── TB Medications ────────────────────────────────────────────────────────
  'Isoniazid 100mg',
  'Isoniazid 300mg',
  'Rifampicin 150mg',
  'Rifampicin 300mg',
  'Pyrazinamide 500mg',
  'Ethambutol 400mg',
  'RHZE (Fixed Dose Combination)',
  'RHZ (Fixed Dose Combination)',

  // ── Gastrointestinal ──────────────────────────────────────────────────────
  'Omeprazole',
  'Omeprazole 20mg',
  'Omeprazole 40mg',
  'Lansoprazole 15mg',
  'Lansoprazole 30mg',
  'Pantoprazole 20mg',
  'Pantoprazole 40mg',
  'Esomeprazole 20mg',
  'Esomeprazole 40mg',
  'Nexium 20mg',
  'Ranitidine 150mg',
  'Ranitidine 300mg',
  'Antacid Suspension',
  'Gaviscon',
  'Rennie Tablets',
  'Loperamide 2mg',
  'Imodium 2mg',
  'Metoclopramide 10mg',
  'Domperidone 10mg',
  'Ondansetron 4mg',
  'Ondansetron 8mg',
  'Bisacodyl 5mg',
  'Senokot Tablets',
  'Lactulose Syrup',
  'Movicol Sachets',

  // ── Mental Health ─────────────────────────────────────────────────────────
  'Fluoxetine 20mg',
  'Fluoxetine 40mg',
  'Sertraline 50mg',
  'Sertraline 100mg',
  'Zoloft 50mg',
  'Escitalopram 10mg',
  'Escitalopram 20mg',
  'Cipralex 10mg',
  'Citalopram 20mg',
  'Amitriptyline 10mg',
  'Amitriptyline 25mg',
  'Amitriptyline 75mg',
  'Clomipramine 25mg',
  'Imipramine 25mg',
  'Venlafaxine 75mg',
  'Venlafaxine 150mg',
  'Mirtazapine 15mg',
  'Mirtazapine 30mg',
  'Alprazolam 0.25mg',
  'Alprazolam 0.5mg',
  'Diazepam 2mg',
  'Diazepam 5mg',
  'Lorazepam 1mg',
  'Clonazepam 0.5mg',
  'Clonazepam 1mg',
  'Haloperidol 1mg',
  'Haloperidol 5mg',
  'Risperidone 1mg',
  'Risperidone 2mg',
  'Quetiapine 25mg',
  'Quetiapine 100mg',
  'Quetiapine 200mg',
  'Olanzapine 5mg',
  'Olanzapine 10mg',
  'Lithium 300mg',
  'Lithium 400mg',
  'Sodium Valproate 200mg',
  'Sodium Valproate 500mg',
  'Carbamazepine 100mg',
  'Carbamazepine 200mg',
  'Tegretol 200mg',
  'Lamotrigine 25mg',
  'Lamotrigine 50mg',
  'Lamotrigine 100mg',

  // ── Thyroid ───────────────────────────────────────────────────────────────
  'Levothyroxine 25mcg',
  'Levothyroxine 50mcg',
  'Levothyroxine 100mcg',
  'Euthyrox 50mcg',
  'Euthyrox 100mcg',
  'Carbimazole 5mg',
  'Carbimazole 10mg',

  // ── Gout / Rheumatology ───────────────────────────────────────────────────
  'Allopurinol 100mg',
  'Allopurinol 300mg',
  'Colchicine 0.5mg',
  'Colchicine 1mg',
  'Methotrexate 2.5mg',
  'Hydroxychloroquine 200mg',
  'Sulfasalazine 500mg',

  // ── Antihistamines / Allergies ────────────────────────────────────────────
  'Cetirizine 10mg',
  'Loratadine 10mg',
  'Clarityne 10mg',
  'Fexofenadine 120mg',
  'Fexofenadine 180mg',
  'Telfast 180mg',
  'Chlorpheniramine 4mg',
  'Promethazine 10mg',
  'Promethazine 25mg',

  // ── Vitamins / Supplements ────────────────────────────────────────────────
  'Folic Acid 1mg',
  'Folic Acid 5mg',
  'Iron (Ferrous Sulphate) 200mg',
  'Ferrograd',
  'Vitamin B12 (Cyanocobalamin) 1000mcg',
  'Vitamin D3 1000IU',
  'Vitamin D3 5000IU',
  'Calcium + Vitamin D3',
  'Calcium Carbonate 500mg',
  'Multivitamin',
  'Zinc 20mg',
  'Magnesium 250mg',
  'Omega-3 Fish Oil 1000mg',

  // ── Antifungals ───────────────────────────────────────────────────────────
  'Fluconazole 150mg',
  'Fluconazole 200mg',
  'Itraconazole 100mg',
  'Clotrimazole Cream',
  'Miconazole Cream',

  // ── Eye / ENT ─────────────────────────────────────────────────────────────
  'Timolol Eye Drops 0.5%',
  'Latanoprost Eye Drops',
  'Xalatan Eye Drops',
  'Prednisolone Eye Drops',
  'Ciprofloxacin Eye Drops',
  'Oxymetazoline Nasal Spray',
  'Budesonide Nasal Spray',
  'Fluticasone Nasal Spray',
  'Nasonex Nasal Spray',
  'Otrivin Nasal Spray',

  // ── Other Common ──────────────────────────────────────────────────────────
  'Dexamethasone 0.5mg',
  'Dexamethasone 4mg',
  'Methylprednisolone 4mg',
  'Hydrocortisone 10mg',
  'Hydrocortisone Cream 1%',
  'Betamethasone Cream',
  'Benzyl Benzoate Lotion',
  'Permethrin Cream 5%',
  'Silver Sulfadiazine Cream',
  'Bacitracin/Neomycin Ointment',

  // ── Malaria (Uganda EMHSLU 2023) ─────────────────────────────────────────
  'Artemether/Lumefantrine 20/120mg',
  'Artemether/Lumefantrine 80/480mg',
  'Coartem 20/120mg',
  'Coartem 80/480mg',
  'Artesunate 50mg',
  'Artesunate 100mg',
  'Artesunate 200mg',
  'Artesunate Injection 60mg',
  'Artemether Injection 80mg',
  'Quinine 300mg',
  'Quinine Sulphate 300mg',
  'Quinine Injection 600mg/2ml',
  'Dihydroartemisinin/Piperaquine 40/320mg',
  'Amodiaquine 200mg',
  'Sulfadoxine/Pyrimethamine 500/25mg',
  'Fansidar 500/25mg',

  // ── Epilepsy / Neurology (Uganda first-line) ──────────────────────────────
  'Phenobarbital 30mg',
  'Phenobarbital 60mg',
  'Phenobarbital 100mg',
  'Phenytoin 50mg',
  'Phenytoin 100mg',
  'Dilantin 100mg',
  'Levetiracetam 250mg',
  'Levetiracetam 500mg',
  'Levetiracetam 1000mg',
  'Keppra 500mg',
  'Ethosuximide 250mg',
  'Clonazepam 2mg',
  'Gabapentin 100mg',
  'Gabapentin 300mg',
  'Gabapentin 400mg',

  // ── Hypertension in Pregnancy / Obstetric ────────────────────────────────
  'Captopril 12.5mg',
  'Captopril 25mg',
  'Captopril 50mg',
  'Methyldopa 250mg',
  'Methyldopa 500mg',
  'Aldomet 250mg',
  'Hydralazine 25mg',
  'Hydralazine 50mg',
  'Hydralazine Injection 20mg',
  'Labetalol 100mg',
  'Labetalol 200mg',
  'Magnesium Sulphate 50% Injection',
  'Nifedipine 5mg Immediate Release',

  // ── Asthma / COPD Uganda additions ───────────────────────────────────────
  'Aminophylline 100mg',
  'Aminophylline 200mg',
  'Aminophylline Injection 250mg/10ml',
  'Salbutamol Nebule 2.5mg',
  'Salbutamol Syrup 2mg/5ml',
  'Salbutamol Tablets 2mg',
  'Salbutamol Tablets 4mg',

  // ── Mental Health Uganda additions ───────────────────────────────────────
  'Chlorpromazine 25mg',
  'Chlorpromazine 50mg',
  'Chlorpromazine 100mg',
  'Largactil 100mg',
  'Fluphenazine Decanoate 25mg/ml',
  'Fluphenazine 1mg',
  'Trifluoperazine 5mg',
  'Thioridazine 25mg',
  'Thioridazine 100mg',
  'Trihexyphenidyl 2mg',
  'Trihexyphenidyl 5mg',
  'Benzhexol 2mg',
  'Benzhexol 5mg',
  'Procyclidine 5mg',
  'Biperiden 2mg',
  'Zuclopenthixol 25mg',
  'Clopixol 200mg/ml Depot',
  'Phenobarbitone 30mg',

  // ── HIV / ARVs Uganda additions ───────────────────────────────────────────
  'Dolutegravir/Lamivudine 50/300mg',
  'Abacavir/Lamivudine 600/300mg',
  'Abacavir/Lamivudine/Dolutegravir',
  'Lopinavir/Ritonavir 40/10mg/ml Syrup',
  'Efavirenz/Lamivudine/Tenofovir 600/300/300mg',
  'TLE (Tenofovir/Lamivudine/Efavirenz)',
  'Zidovudine/Lamivudine 300/150mg',
  'Zidovudine/Lamivudine/Nevirapine',
  'Rilpivirine 25mg',
  'Raltegravir 400mg',
  'Maraviroc 150mg',
  'Cobicistat 150mg',
  'Elvitegravir/Cobicistat/Emtricitabine/Tenofovir',
  'Cabotegravir 30mg',
  'Cabotegravir/Rilpivirine Injection',

  // ── TB Uganda additions ───────────────────────────────────────────────────
  'Rifabutin 150mg',
  'Rifabutin 300mg',
  'Bedaquiline 100mg',
  'Delamanid 50mg',
  'Linezolid 300mg',
  'Linezolid 600mg',
  'Clofazimine 50mg',
  'Clofazimine 100mg',
  'Cycloserine 250mg',
  'Amikacin 500mg Injection',
  'Moxifloxacin 400mg',
  'Levofloxacin 250mg',
  'Levofloxacin 500mg',
  'Levofloxacin 750mg',
  'Pyridoxine 25mg',
  'Pyridoxine 50mg',
  'Pyridoxine 100mg',
  'Vitamin B6 25mg',

  // ── Antiparasitics / Tropical Diseases (Uganda) ───────────────────────────
  'Albendazole 200mg',
  'Albendazole 400mg',
  'Mebendazole 100mg',
  'Mebendazole 500mg',
  'Ivermectin 3mg',
  'Ivermectin 6mg',
  'Mectizan 3mg',
  'Praziquantel 150mg',
  'Praziquantel 600mg',
  'Diethylcarbamazine 50mg',
  'Diethylcarbamazine 100mg',
  'Niclosamide 500mg',
  'Levamisole 50mg',
  'Pentamidine 200mg Injection',
  'Suramin Injection',
  'Melarsoprol Injection',
  'Eflornithine Infusion 400mg/250ml',
  'Nifurtimox 120mg',

  // ── Antibiotics Uganda additions ─────────────────────────────────────────
  'Ampicillin 250mg',
  'Ampicillin 500mg',
  'Ampicillin Injection 500mg',
  'Ampicillin Injection 1g',
  'Benzylpenicillin (Penicillin G) 1MU Injection',
  'Benzylpenicillin 5MU Injection',
  'Benzathine Penicillin 1.2MU Injection',
  'Benzathine Penicillin 2.4MU Injection',
  'Procaine Penicillin Injection 3MU',
  'Gentamicin 80mg Injection',
  'Gentamicin 160mg Injection',
  'Trimethoprim 200mg',
  'Nalidixic Acid 500mg',
  'Chloramphenicol 250mg',
  'Chloramphenicol Injection 1g',
  'Ceftriaxone 250mg Injection',
  'Ceftriaxone 500mg Injection',
  'Ceftriaxone 1g Injection',
  'Cefotaxime 500mg Injection',
  'Cefotaxime 1g Injection',
  'Vancomycin 500mg Injection',
  'Rifampicin 450mg',
  'Tetracycline 250mg',
  'Tetracycline 500mg',
  'Spectinomycin 2g Injection',

  // ── Sickle Cell Disease ───────────────────────────────────────────────────
  'Hydroxyurea 500mg',
  'Hydroxycarbamide 500mg',
  'Deferasirox 250mg',
  'Deferasirox 500mg',
  'Desferrioxamine Injection',

  // ── Antifungal Uganda additions ───────────────────────────────────────────
  'Nystatin 100,000IU Oral Drops',
  'Nystatin Suspension 100,000IU/ml',
  'Nystatin Pessary 100,000IU',
  'Griseofulvin 125mg',
  'Griseofulvin 500mg',
  'Amphotericin B Injection',
  'Voriconazole 200mg',
  'Fluconazole 50mg',

  // ── Rheumatology additions ─────────────────────────────────────────────────
  'Leflunomide 10mg',
  'Leflunomide 20mg',
  'Azathioprine 50mg',
  'Chloroquine 150mg',
  'Chloroquine Phosphate 250mg',
  'Indomethacin 25mg',
  'Indomethacin 50mg',
  'Celecoxib 100mg',
  'Celecoxib 200mg',

  // ── Thyroid additions ──────────────────────────────────────────────────────
  'Propylthiouracil 50mg',
  'Propylthiouracil 100mg',
  'Lugol Iodine Solution',

  // ── Reproductive / Hormonal ────────────────────────────────────────────────
  'Oxytocin 10IU Injection',
  'Misoprostol 200mcg',
  'Misoprostol 25mcg',
  'Progesterone 200mg',
  'Medroxyprogesterone 150mg Injection',
  'Depo-Provera 150mg',
  'Levonorgestrel/Ethinylestradiol 150/30mcg',
  'Norethisterone 5mg',
  'Clomiphene 50mg',

  // ── Chronic Kidney Disease ─────────────────────────────────────────────────
  'Erythropoietin 2000IU Injection',
  'Erythropoietin 4000IU Injection',
  'Epoetin Alfa Injection',
  'Calcium Acetate 667mg',
  'Sevelamer 800mg',
  'Sodium Bicarbonate 500mg',
  'Kayexalate (Sodium Polystyrene) Powder',

  // ── Vitamins / Micronutrients Uganda ──────────────────────────────────────
  'Ferrous Sulphate Syrup 25mg/ml',
  'Iron/Folic Acid 200mg/0.4mg',
  'Vitamin A 200,000IU Capsule',
  'Vitamin A 100,000IU Drops',
  'Vitamin C 100mg',
  'Vitamin C 250mg',
  'Vitamin C 500mg',
  'Thiamine (Vitamin B1) 100mg',
  'Riboflavin (Vitamin B2) 5mg',
  'Nicotinamide 50mg',
  'Pyridoxine (Vitamin B6) 25mg',
  'Zinc Sulphate 20mg',
  'Zinc Sulphate 10mg Syrup',
  'Oral Rehydration Salts (ORS)',

  // ── Cardiovascular Uganda additions ──────────────────────────────────────
  'Streptokinase 1.5MU Injection',
  'Dopamine Injection',
  'Dobutamine Injection',
  'Adrenaline (Epinephrine) 1mg/ml Injection',
  'Noradrenaline Injection',
  'Sodium Nitroprusside Injection',
  'Amiodarone 100mg',
  'Amiodarone 200mg',
  'Amiodarone Injection 150mg',
  'Verapamil 40mg',
  'Verapamil 80mg',
  'Diltiazem 60mg',
  'Diltiazem 90mg',
  'Diltiazem 120mg',
  'Adenosine Injection 6mg',
  'Atropine 0.6mg Injection',
  'Glyceryl Trinitrate (GTN) Spray',
  'Glyceryl Trinitrate Tablets 0.5mg',
  'Eplerenone 25mg',
  'Eplerenone 50mg',
  'Ivabradine 5mg',
  'Ivabradine 7.5mg',
  'Sacubitril/Valsartan 49/51mg',
  'Entresto 49/51mg',

  // ── Gastrointestinal Uganda additions ────────────────────────────────────
  'Sucralfate 1g',
  'Mesalazine 400mg',
  'Mesalazine 800mg',
  'Sulfasalazine 1g Enema',
  'Hyoscine 10mg',
  'Hyoscine Butylbromide 20mg Injection',
  'Buscopan 10mg',
  'Activated Charcoal',
  'Magnesium Hydroxide Suspension',
  'Aluminium Hydroxide 500mg',
];

/// Filter medications by query (case-insensitive, matches anywhere in string).
List<String> searchMedications(String query, {int limit = 10}) {
  if (query.trim().isEmpty) return [];
  final q = query.toLowerCase();
  return kCommonMedications
      .where((med) => med.toLowerCase().contains(q))
      .take(limit)
      .toList();
}
